name: CD1

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --global prettier
      - run: prettier --check p2p

  deploy:
    name: Deploy
    needs: prettier
    env:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: echo ${known_hosts} > ~/.ssh/known_hosts
      - run: echo ${private_key} > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: echo Hello > ~/Hello
      - run: scp ~/Hello stun@40.85.141.137:~/