name: CD

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --global prettier
      - run: prettier --check p2p

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve secret
        env:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: mkdir ~/.ssh
        run: echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        run: ls ~/.ssh