name: CD1

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --global prettier
      - run: prettier --check p2p

  deploy:
    name: Deploy
    needs: prettier
    env:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: echo ${known_hosts} > ~/.ssh/known_hosts
      - run: echo ${private_key} > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
      - run: echo Hello > ~/Hello
      - run: scp ~/Hello stun@40.85.141.137:~/

  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh stun@40.85.141.137
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}