name: stun CD

on:
  push:
    paths:
      - 'stunserver/*'
      - '.github/workflows/stun.yml'

jobs:

  test:
    name: Stun tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ test/attribute_test.cpp -o test1
      - run: ./test1
      - run: g++ test/handler_test.cpp -o test1
      - run: ./test1

  deploy:
    name: Deploy
    needs: test
    env:
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: echo "$known_hosts" > ~/.ssh/known_hosts
      - run: echo "$private_key" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: scp -r stunserver Makefile stun@40.85.141.137:~/
      - run: ssh stun@40.85.141.137 make stun